opt:
    lr: 0.00001
    betas: [0.9, 0.999]
    eps: 0.000001
    weight_decay: 0.0
    correct_bias: false
    clipping: local
    max_grad_norm: 1.0
    exp_avg_sq_value: 0.00001
    etta: 1.0
    model_name: bert


train:
    model_checkpoint: albert-base-v2
    max_epoch: 1
    batch_size: 8
    seed: 123
    classifier_dropout: 0.0
    val_check_interval: 12

data:
    task: rte

global_:
    wandb_project_name: "cs459opt"
    wandb_run_name: "rte-finetuning"
    wandb_run_tags: []
    save_path_root: "/scratch/izar/skorokho/cs439opt_scratch"
    save_model_flg: True
    save_model_path: null
    use_wandb: False
    model_name_or_path: albert-base-v2