data:
  cache_dir: /Clipped-AdaGrad-and-Adam/ALBERT_fine_tuning/hf_cache/
  tasks:
    - qnli

train:
  model_checkpoint: roberta-large
  max_epoch: 5
  batch_size: 16
  seed: 42
  max_length: 128
  classifier_dropout: 0.1
  val_check_interval: 10

opt:
  name: adam-clip
  lr: 2e-5
  betas: [0.9, 0.999]
  eps: 1e-8
  weight_decay: 0.01
  correct_bias: true
  clipping: no
  max_grad_norm: 1.0
  exp_avg_sq_value: 1e-6