opt:
    lr: 0.00001
    betas: [0.9, 0.999]
    eps: 0.000001
    weight_decay: 0.0
    correct_bias: false
    clipping: local
    max_grad_norm: 1.0
    exp_avg_sq_value: 0.00001
    etta: 1.0

train:
    model_checkpoint: albert-base-v2
    max_epoch: 1
    batch_size: 8
    seed: 123
    classifier_dropout: 0.0
    val_check_interval: 12

data:
    task: rte
