opt:
    lr: 0.1
    betas: [0.9, 0.999]
    eps: 1e-8
    weight_decay: 5e-4
    correct_bias: false
    clipping: local
    max_grad_norm: 1.0
    exp_avg_sq_value: 0.00001
    etta: 1.0

train:
    num_classes: 10
    max_epoch: 200
    batch_size: 128
    seed: 42
    classifier_dropout: 0.0
    val_check_interval: 50

global_:
    wandb_project_name: "cs459opt"
    wandb_run_name: "1st"
    wandb_run_tags: []
    save_path: "/scratch/izar/skorokho/cs439opt_scratch"
    save_model_flg: True
    save_model_path: null
    use_wandb: True
